language: cpp
services:
  - docker
matrix:
  include:
    - env: PLATFORM=pc
    - env: PLATFORM=switch
    - env: PLATFORM=wiiu
script:
  - docker run -v $(pwd):/code registry.gitlab.com/4tu/spheal
               /bin/bash -c "cd /code && make -f Makefile.$PLATFORM"
